CREATE DATABASE MvetDB
USE MvetDB

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role ENUM('doc','user', 'admin') DEFAULT 'doc',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
